[[constraint]]
  name = "github.com/go-kit/kit"
  version = "0.5.0"

[[constraint]]
  name = "github.com/iwilltry42/edgecast"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.9.0-pre1"
